### ISSUE TITLE
Make animation transition configurable with prop

### ISSUE THREAD

**Issue by kristofferandreasen** [kristofferandreasen/react-announcement#7]
This enables the user to decide the speed of the animation. It is currently set at 300 ms. Must be added to main file and added to documentation table for all properties.

**Comment by pbrickles** [comment]
I have a solution for this, although happy for you to assign it to me for #hacktoberfest (and wait till then) if you like.

**Comment by kristofferandreasen** [comment]
Great to hear!
The solution is currently using the CSS transition timer and a timer in the react component.
I didn't have an immediate solution without including styled-components.

**Comment by kristofferandreasen** [comment]
Thank you for the great solution and contribution! 
I think it makes the small component even more attractive to use and more flexible.
